apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  labels:
    name: secret-volume
spec:    
  containers:
    - name: myapp-container
      image: registry.cn-hangzhou.aliyuncs.com/wangyangshare/share:myappv1.0
      volumeMounts:
        - name: volumes12
          mountPath: "/data"
  volumes:
    - name: volumes12
      secret:
        secretName: mysecret 
        defaultMode: 0644 # Set permission