module "k8s-cvm" {
  source = "./k8s-cvm"
  ssh_key_private_key_path = var.ssh_key_private_key_path
  ssh_key_public_key_path = var.ssh_key_public_key_path
  cvm_availability_zone = var.cvm_availability_zone
  cvm_charge_type = var.cvm_charge_type
  cvm_login_user = var.cvm_login_user
  cvm_os_regex = var.cvm_os_regex
  k8s_cluster = var.k8s_cluster
  cvm_cfs_enabled = var.cfs_enabled
  cvm_cfs_secret_id = var.secret_id
  cvm_cfs_secret_key = var.secret_key
  cvm_cfs_csi_secret = var.cfs_csi_secret
  k8s_version = var.k8s_version
  k8s_cidr = var.k8s_cidr
  k8s_cri_dockerd_version = var.k8s_cri_dockerd_version
  k8s_cfssl_version = var.k8s_cfssl_version
  k8s_helm_version = var.k8s_helm_version
  k8s_helm_enabled = var.k8s_helm_enabled
  k8s_cfssl_enabled = var.k8s_cfssl_enabled
  vpc_id = var.vpc_id
  subnet_id = var.subnet_id
  cfs_cidr = var.cfs_allow_cidr
}