apiVersion: v1
kind: PersistentVolume                                                                                                                                      
metadata:
  name: nfspv1
spec:  
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs: 
    path: /opt/cfs_data
    server: 172.19.0.11 # CFS server IP

---
apiVersion: v1
kind: PersistentVolume                                                                                                                                      
metadata:
  name: nfspv2
spec:  
  capacity:
    storage: 1.2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs: 
    path: /opt/cfs_data
    server: 172.19.0.11 # CFS server IP