apiVersion: batch/v1
kind: Job
metadata:
  name: rand
spec:
  completions: 10
  parallelism: 5                                                                                                                                              
  template:
    metadata:
      name: rand
    spec:
      containers:
      - name: rand
        image: registry.cn-hangzhou.aliyuncs.com/wangyangshare/share:randexitv1
      restartPolicy: Never