
apiVersion: v1
kind: Service
metadata:  
  name: myapp-clusterip
  namespace: default                                                                                                                                       
spec:      
  type: ClusterIP
  selector:
    app: myapp
    release: stabel
    svc: clusterip
  sessionAffinity: ClientIP # Enable session affinity based on client IP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600 # Default session affinity timeout (10800 seconds)
  ports:   
  - name: http
    port: 80
    targetPort: 80